name: predestination
channels:
- defaults
dependencies:
- python=3.6.4
- pip=9.0.1
- pip:
  - eventlet==0.22.0
  - flake8==3.5.0
  - flask==0.12.2
  - flask-socketio==2.9.2
  - gunicorn==19.7.1
  - numpy==1.14.0
  - scikit-learn=0.19.1
  - scipy=1.0.0
  - torch==0.3.0.post4
