#!/usr/bin/env zsh

set -e
set -u

cd $(dirname $0)

PORT=${PORT:-8080}

if [[ -d env ]]; then
  GUNICORN=env/bin/gunicorn
  PYTHONPATH=src,env/lib/python3.6/site-packages
else
  GUNICORN=gunicorn
  PYTHONPATH=src
fi

PID=0

function start_app {
  zparseopts -- -file:=INPUT_FILE
  INPUT_FILE=${INPUT_FILE[2]} \
  $GUNICORN \
    --bind="0.0.0.0:${PORT}" \
    --pythonpath=$PYTHONPATH \
    --worker-class=eventlet \
    --workers=1 \
    web:app &
  PID="$!"
}

function stop_app {
  EXIT_STATUS=$?
  if (( $PID )); then
    kill $PID
    wait $PID
    exit 0
  else
    exit $EXIT_STATUS
  fi
}

start_app $@
trap stop_app HUP INT QUIT TERM

wait $PID
