#!/usr/bin/env zsh

set -e
set -u

cd $(dirname $0)

PORT=${PORT:-8080}

export PYTHONPATH=src:${PYTHONPATH:-}

PID=0

function start_app {
  gunicorn \
    --bind="0.0.0.0:${PORT}" \
    --pythonpath=$PYTHONPATH \
    --worker-class=eventlet \
    --workers=1 \
    web:app \
    -- $@ &
  PID="$!"
}

function stop_app {
  EXIT_STATUS=$?
  if (( $PID )); then
    kill $PID
    wait $PID
    exit 0
  else
    exit $EXIT_STATUS
  fi
}

start_app $@
trap stop_app HUP INT QUIT TERM

wait $PID
